---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Run the snapraid status command and check output for errors.
      ansible.builtin.command:
        cmd: snapraid status
      register: snapraid_status
      failed_when: snapraid_status.rc != 0 and "WARNING!" not in snapraid_status.stderr
      changed_when: true
