---

tesseract_log_file: /var/log/tesseract.log
tesseract_files_path: /root

tesseract_scripts_repo: https://github.com/ben16w/tesseract-scripts.git

local_backup_paths: []

local_backup_destination: /media/backups

local_backup_keep_daily: 4
local_backup_keep_weekly: 3
local_backup_keep_monthly: 2

local_backup_minute: 0
local_backup_hour: 0
local_backup_day: "*"

email_host: ~
email_port: ~
email_username: ~
email_password: ~
