---

tesseract_files_path: "/root"

tesseract_log_file: "/var/log/tesseract.log"

email_host: ~
email_port: ~
email_username: ~
email_password: ~

log_monitor_email_to: ~
log_monitor_poll_interval: 15 # Polling interval in minutes
