---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Gather package facts.
      ansible.builtin.package_facts:

    - name: Assert msmtp is installed.
      ansible.builtin.assert:
        that: "'msmtp' in ansible_facts.packages"

    - name: Inject a test error into the journal.
      ansible.builtin.command:
        cmd: logger -p err "molecule test error"
      changed_when: false

    - name: Run the log monitor script in dry run mode.
      ansible.builtin.command:
        cmd: "{{ tesseract_files_path }}/scripts/monitor.sh --dry"
      register: script_run
      failed_when: script_run.rc != 0
      changed_when: false

    - name: Check the tesseract log file.
      ansible.builtin.slurp:
        src: "{{ tesseract_log_file }}"
      register: log_file

    - name: Assert log file contains expected entries.
      ansible.builtin.assert:
        that:
          - "'Checking journal for new errors' in log_file.content | b64decode"
          - "'Errors found' in log_file.content | b64decode"

    - name: Shellcheck the log monitor script.
      ansible.builtin.command:
        cmd: shellcheck {{ tesseract_files_path }}/scripts/monitor.sh
      changed_when: false

    - name: Shellcheck the Docker monitor script.
      ansible.builtin.command:
        cmd: shellcheck {{ tesseract_files_path }}/scripts/monitor_docker.sh
      changed_when: false
