---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Gather package facts.
      ansible.builtin.package_facts:

    - name: Assert python3-docker is installed.
      ansible.builtin.assert:
        that: "'python3-docker' in ansible_facts.packages"

    - name: Assert monitors directory exists.
      ansible.builtin.stat:
        path: "{{ monitor_scripts_path }}/monitors"
      register: monitors_dir

    - name: Verify monitors directory.
      ansible.builtin.assert:
        that:
          - monitors_dir.stat.exists
          - monitors_dir.stat.isdir

    - name: Assert monitor scripts are present.
      ansible.builtin.stat:
        path: "{{ item }}"
      register: script_stat
      loop:
        - "{{ monitor_scripts_path }}/monitor.py"
        - "{{ monitor_scripts_path }}/monitors/journal.sh"
        - "{{ monitor_scripts_path }}/monitors/docker.py"

    - name: Verify monitor scripts exist.
      ansible.builtin.assert:
        that: item.stat.exists
      loop: "{{ script_stat.results }}"

    - name: Inject a test error into the journal.
      ansible.builtin.command:
        cmd: logger -p err "molecule test error"
      changed_when: false

    - name: Run the monitor script in dry run mode.
      ansible.builtin.command:
        cmd: "python3 {{ monitor_scripts_path }}/monitor.py {{ monitor_config_file }} --dry"
      register: script_run
      failed_when: script_run.rc != 0
      changed_when: false

    - name: Check the log file.
      ansible.builtin.slurp:
        src: "{{ tesseract_log_file }}"
      register: log_file

    - name: Assert log file contains expected entries.
      ansible.builtin.assert:
        that:
          - "'Checking journal for errors' in log_file.content | b64decode"
          - "'Errors found' in log_file.content | b64decode"

    - name: Shellcheck journal monitor script.
      ansible.builtin.command:
        cmd: shellcheck {{ monitor_scripts_path }}/monitors/journal.sh
      changed_when: false

    - name: Syntax check docker monitor script.
      ansible.builtin.command:
        cmd: python3 -m py_compile {{ monitor_scripts_path }}/monitors/docker.py
      changed_when: false
