---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:

    - name: Inject a test error into the journal.
      ansible.builtin.command:
        cmd: logger -p err "molecule test error"
      changed_when: false

    - name: Run the monitor script in dry run mode.
      ansible.builtin.command:
        cmd: "python3 {{ monitor_install_path }}/monitor.py {{ monitor_config_file }} --dry"
      register: script_run
      failed_when: script_run.rc != 0
      changed_when: false

    - name: Check the log file.
      ansible.builtin.slurp:
        src: "{{ tesseract_log_file }}"
      register: log_file

    - name: Assert log file contains expected entries.
      ansible.builtin.assert:
        that:
          - "'Checking journal for errors' in log_file.content | b64decode"
          - "'Errors found' in log_file.content | b64decode"
