---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - custom

volumes:
  - name: dockersock
    temp: {}

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

steps:
  - name: lint
    image: python:3
    commands:
      - make install-pip
      - export PATH="$$HOME/.local/bin:$$PATH"
      - make lint

  - name: test-changed
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - git fetch origin
      - apk update
      - apk add bash make python3 py3-pip
      - make install-pip
      - export PATH="$$HOME/.local/bin:$$PATH"
      - make test-changed
    when:
      branch:
        exclude:
          - main

  - name: test-distros
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk update
      - apk add bash make python3 py3-pip
      - make install-pip
      - export PATH="$$HOME/.local/bin:$$PATH"
      - DISTRO_LIST="debian12 ubuntu2004 ubuntu2204" make test-distros
    when:
      branch:
        - main

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: EMAIL_HOST
      username:
        from_secret: EMAIL_USERNAME
      password:
        from_secret: EMAIL_PASSWORD
      from:
        from_secret: EMAIL_USERNAME
      port:
        from_secret: EMAIL_PORT
      recipients:
        from_secret: EMAIL_USERNAME
      recipients_only: true
      subject: "Drone: Build #${DRONE_BUILD_NUMBER} failed"
      body: |
        <p>Build #${DRONE_BUILD_NUMBER} failed!</p>
        <ul>
        <li>Repo: ${DRONE_REPO}</li>
        <li>Commit: <code>${DRONE_COMMIT_SHA}</code> by ${DRONE_COMMIT_AUTHOR}</li>
        <li>Link: <a href="${DRONE_BUILD_LINK}">${DRONE_BUILD_LINK}</a></li>
        </ul>
    when:
      branch:
        - main
      status:
        - failure
