---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

# steps:
#   - name: lint
#     commands:
#       - make lint
  - name: test-changed
    commands:
      - make test-changed
