---
kind: pipeline
type: exec
name: test

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - custom

steps:
  - name: lint
    commands:
      - make lint

  - name: test-changed
    commands:
      - git fetch origin
      - make test-changed
    when:
      branch:
        exclude:
          - main

  - name: test-distros
    commands:
      - DISTRO_LIST="debian12 ubuntu2004 ubuntu2204" make test-distros
    when:
      branch:
        - main
