---
kind: pipeline
type: exec
name: test

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
  - name: lint
    commands:
      - make lint
  - name: test
    commands:
      - make test
