---

all:
  hosts:
    192.168.56.11

  vars:
    ansible_connection: ssh
    ansible_user: "vagrant"
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: "/usr/bin/python3"

    tesseract_username: vagrant

    disk_mounts:
      - path: "/media/disk1"
        uuid: "1d60fef0-761a-4d73-99ca-83c2e3de58e4"
      - path: "/media/disk2"
        uuid: "0133f767-9b68-461a-9acd-61327358f725"
      - path: "/media/parity1"
        uuid: "229232cf-1a42-4a0d-af06-fc407b0587f6" 

    # cloud_backup_paths:
    #   - path: /media/storage
    #     keep_months: 3
    #     keep_latest: 14

    mergerfs_disks:
      - /media/disk1
      - /media/disk2
    mergerfs_min_free_space: 100M

    # snapraid_data_disks:
    #   - /media/disk1
    #   - /media/disk2
    # snapraid_parity_disks:
    #   - /media/parity1
    # snapraid_delete_threshold: 100