---
- name: Update repositories cache and install cryptsetup and git.
  ansible.builtin.apt:
    name:
      - cryptsetup
      - git
    update_cache: true

- name: Git checkout common repo.
  ansible.builtin.git:
    repo: "{{ provision_scripts_repo }}"
    dest: "{{ provision_scripts_path }}"
    version: "{{ provision_scripts_version }}"
    force: true
  register: download_common
  retries: 5
  delay: 10
  until: download_common is succeeded

- name: Run provision_disk script.
  loop: "{{ provision_volumes }}"
  ansible.builtin.command:
    cmd: >
      /bin/bash {{ provision_scripts_path }}/{{ provision_scripts_subdir }}/provision_volume.sh
      {% if item.generate_data == true %}-d{% endif %}
      -s '{{ item.size }}'
      -p '{{ item.password }}'
      '{{ item.volume_file }}'
    creates: "{{ item.volume_file }}"
