---
- name: Converge
  hosts: all
  vars:
    tesseract_email_username: "email@email.com"
    tesseract_email_host: "email.com"
    tesseract_email_port: "465"
    tesseract_email_password: "password"
  roles:
    - role: tesseract.system.local_backup
