---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - tesseract_email_host is not none
      - tesseract_email_port is not none
      - tesseract_email_username is not none
      - tesseract_email_password is not none
      - monitor_alert_email is not none

- name: Install cron and python3-docker.
  ansible.builtin.package:
    name:
      - cron
      - python3-docker
    update_cache: true

- name: Create monitor config directory.
  ansible.builtin.file:
    path: "{{ monitor_config_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Write monitor config file.
  no_log: true
  ansible.builtin.copy:
    dest: "{{ monitor_config_file }}"
    owner: root
    group: root
    mode: '0600'
    content: |
      EMAIL_TO={{ monitor_alert_email }}
      EMAIL_FROM={{ tesseract_email_username }}
      EMAIL_HOST={{ tesseract_email_host }}
      EMAIL_PORT={{ tesseract_email_port }}
      EMAIL_PASSWORD={{ tesseract_email_password }}
      LOG_FILE={{ tesseract_log_file }}
      POLL_INTERVAL={{ monitor_poll_interval }}
      EXCLUDE_PATTERNS={{ monitor_exclude_patterns | join('|') }}
      DOCKER_EXCLUDE_CONTAINERS={{ monitor_docker_exclude_containers | join(' ') }}
      DOCKER_EXCLUDE_PATTERNS={{ monitor_docker_exclude_patterns | join('|') }}

- name: Create install directory.
  ansible.builtin.file:
    path: "{{ monitor_install_path }}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Copy monitor scripts.
  ansible.builtin.copy:
    src: monitor/
    dest: "{{ monitor_install_path }}/"
    owner: root
    group: root
    mode: '0755'

- name: Ensure cron job to monitor for errors is present.
  when: monitor_enabled | bool
  ansible.builtin.cron:
    name: "Monitor system logs for errors."
    minute: "*/{{ monitor_poll_interval }}"
    job: "flock -n /tmp/monitor.lockfile python3 {{ monitor_install_path }}/monitor.py {{ monitor_config_file }}"

- name: Ensure cron job to monitor for errors is absent.
  when: not (monitor_enabled | bool)
  ansible.builtin.cron:
    name: "Monitor system logs for errors."
    state: absent
