---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - email_host is not none
      - email_port is not none
      - email_username is not none
      - email_password is not none
      - monitor_email_to is not none

- name: Install msmtp and cron.
  ansible.builtin.package:
    name:
      - msmtp
      - cron
    update_cache: true

- name: Add msmtp email global config.
  no_log: true
  ansible.builtin.blockinfile:
    path: /etc/msmtprc
    create: true
    owner: root
    group: root
    mode: '0644'
    block: |
      account default
      tls on
      tls_starttls off
      tls_certcheck off
      auth login
      host "{{ email_host }}"
      port "{{ email_port }}"
      user "{{ email_username }}"
      from "{{ email_username }}"
      password "{{ email_password }}"

- name: Create scripts directory if it does not exist.
  ansible.builtin.file:
    path: "{{ monitor_scripts_path }}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Create log monitor cursor directory if it does not exist.
  ansible.builtin.file:
    path: "{{ monitor_cursor_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Template log monitor script to scripts directory.
  ansible.builtin.template:
    src: templates/monitor.sh.j2
    dest: "{{ monitor_scripts_path }}/monitor.sh"
    owner: root
    group: root
    mode: '0755'

- name: Ensure cron job to monitor logs for errors is present.
  when: monitor_enabled | bool
  ansible.builtin.cron:
    name: "Monitor system logs for errors."
    minute: "*/{{ monitor_poll_interval }}"
    job: "flock -n /tmp/monitor.lockfile {{ monitor_scripts_path }}/monitor.sh"

- name: Ensure cron job to monitor logs for errors is absent.
  when: not (monitor_enabled | bool)
  ansible.builtin.cron:
    name: "Monitor system logs for errors."
    state: absent

- name: Template Docker monitor script to scripts directory.
  ansible.builtin.template:
    src: templates/monitor_docker.sh.j2
    dest: "{{ monitor_scripts_path }}/monitor_docker.sh"
    owner: root
    group: root
    mode: '0755'

- name: Ensure cron job to monitor Docker containers is present.
  when: monitor_docker_enabled | bool
  ansible.builtin.cron:
    name: "Monitor Docker containers for problems."
    minute: "*/{{ monitor_docker_poll_interval }}"
    job: "flock -n /tmp/monitor_docker.lockfile {{ monitor_scripts_path }}/monitor_docker.sh"

- name: Ensure cron job to monitor Docker containers is absent.
  when: not (monitor_docker_enabled | bool)
  ansible.builtin.cron:
    name: "Monitor Docker containers for problems."
    state: absent
