---
- name: Converge
  hosts: all
  vars:
    email_username: "email@email.com"
    email_host: "email.com"
    email_port: "465"
    email_password: "password"
    kopia_backup_bb_key_id: "key_id"
    kopia_backup_bb_key: "key"
    kopia_backup_bb_bucket: "bucket"
    kopia_backup_password: "password"
  roles:
    - role: kopia_backup
