---

- name: Clean apt cache.
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: false

- name: Remove unused packages.
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Check if 'pip cache' command exists.
  ansible.builtin.command:
    cmd: pip help
  register: pip_cache_supported
  changed_when: false

- name: Clean pip cache.
  ansible.builtin.command:
    cmd: pip cache purge
  changed_when: false
  when: "'wheel cache.' in pip_cache_supported.stdout"

- name: Clean journal logs.
  ansible.builtin.command:
    cmd: "journalctl --vacuum-time={{ clean_log_age_days }}d"
  changed_when: false

- name: Find old log files.
  ansible.builtin.find:
    paths:
      - /var/log
    patterns:
      - "*.log"
      - "*.gz"
      - "*.1"
      - "*.old"
    age: "{{ clean_log_age_days }}d"
    recurse: true
  register: old_logs

- name: Delete old log files.
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_logs.files }}"

- name: Check if Docker is installed in /bin.
  ansible.builtin.stat:
    path: /bin/docker
  register: docker_bin_bin

- name: Check if Docker is installed in /usr/bin.
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_bin_usr

- name: Prune Docker system if installed.
  ansible.builtin.command:
    cmd: docker system prune -af
  when: docker_bin_bin.stat.exists or docker_bin_usr.stat.exists
  changed_when: false
