---
- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - email_host is not none
      - email_port is not none
      - email_username is not none
      - email_password is not none
      - kopia_backup_bb_key_id is not none
      - kopia_backup_bb_key is not none
      - kopia_backup_bb_bucket is not none
      - kopia_backup_password is not none

- name: Add an Apt signing key for Kopia.
  ansible.builtin.apt_key:
    url: https://kopia.io/signing-key

- name: Add Kopia repository into sources list.
  ansible.builtin.apt_repository:
    repo: deb http://packages.kopia.io/apt/ stable main
    state: present
    update_cache: true

- name: Install Kopia and fuse.
  ansible.builtin.package:
    name:
      - kopia
      - fuse
      - msmtp
    state: present

- name: Add msmtp email global config.
  no_log: true
  ansible.builtin.blockinfile:
    path: /etc/msmtprc
    create: true
    owner: root
    group: root
    mode: 0644
    block: |
      account default
      tls on
      tls_starttls off
      tls_certcheck off
      auth login
      host "{{ email_host }}"
      port "{{ email_port }}"
      user "{{ email_username }}"
      from "{{ email_username }}"
      password "{{ email_password }}"

- name: Create scripts directory if it does not exist.
  ansible.builtin.file:
    path: "{{ files_path }}/scripts"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Git checkout scripts to scripts directory.
  ansible.builtin.git:
    repo: "{{ scripts_repo }}"
    dest: "{{ files_path }}/scripts"
    version: main
    force: true

- name: Write .env file.
  ansible.builtin.blockinfile:
    path: "{{ files_path }}/scripts/.env"
    marker: "# {mark} kopia_backup ANSIBLE MANAGED BLOCK"
    create: true
    owner: root
    group: root
    mode: 0644
    block: |
      KOPIA_BACKUP_LOG_DIR="{{ kopia_backup_log_dir }}"
      KOPIA_BACKUP_LOG_LEVEL="{{ kopia_backup_log_level }}"
      KOPIA_BACKUP_VERIFY_PERCENT="{{ kopia_backup_verify_percent }}"
      LOG_FILE="{{ log_file }}"
      EMAIL_USERNAME="{{ email_username }}"

- name: Make sure kopia logging directory exists.
  ansible.builtin.file:
    path: "{{ kopia_backup_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Connect Kopia repo.
  register: result
  changed_when: "'Connected to repository' in result.stdout"
  when: kopia_backup_paths | length > 0
  no_log: true
  ansible.builtin.command:
    cmd: >
      kopia repository connect b2
      --bucket={{ kopia_backup_bb_bucket }}
      --key-id={{ kopia_backup_bb_key_id }}
      --key={{ kopia_backup_bb_key }}
      --password={{ kopia_backup_password }}

# kopia policy set --compression=zstd path
# kopia policy set --global \
# --add-never-compress ".zip" \
# It's possible to specify targets, like appdata
# [<target>]  Target of a policy ('global','user@host','@host') or a path

- name: Set Kopia policies for paths.
  ansible.builtin.command:
    cmd: >
      kopia policy set
      --keep-hourly 0
      --keep-daily {{ item.keep_days | default("0", true) }}
      --keep-weekly {{ item.keep_weeks | default("0", true) }}
      --keep-monthly {{ item.keep_months | default("0", true) }}
      --keep-annual {{ item.keep_years | default("0", true) }}
      --keep-latest {{ item.keep_latest | default("8", true) }}
      {{ item.path }}
  with_items: "{{ kopia_backup_paths }}"
  when: kopia_backup_paths | length > 0

# kopia policy set --add-ignore /Downloads @tepig
# could be put in a for loop in the section above to add in --add-ignore
# ignored paths would be the same for all paths
# {% for path in kopia_backup_ignored %} --add-ignore {{ path }}{% endfor %}

- name: Initialize an empty string for Kopia backup paths.
  ansible.builtin.set_fact:
    kopia_backup_paths: ""
  when: kopia_backup_paths | length > 0

- name: Generate string of Kopia backup paths.
  ansible.builtin.set_fact:
    kopia_backup_paths: "{{ kopia_backup_paths }} {{ item.path }}"
  with_items: "{{ kopia_backup_paths }}"
  when: kopia_backup_paths | length > 0

- name: Add paths for backup to cron.
  ansible.builtin.cron:
    name: "Kopia backup."
    minute: "0"
    hour: "2"
    # job: "{ kopia snapshot {{ item.path }}; } 2>&1 | bash {{ files_path }}/scripts/error.sh"
    job: "bash {{ files_path }}/scripts/kopia_backup.sh{{ kopia_backup_paths }}"
  when: kopia_backup_paths | length > 0
