---

- name: Install software.
  ansible.builtin.apt:
    pkg:
      - cryptsetup
    update_cache: true

- name: Make sure disk mount paths exists.
  loop: "{{ mount_disks }}"
  no_log: true
  ansible.builtin.file:
    path: "{{ item.mount_path }}"
    state: directory
    mode: '0755'

- name: Decrypt disks.
  loop: "{{ mount_disks }}"
  no_log: true
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      echo -n "{{ item.password }}" |
      cryptsetup luksOpen "{{ item.volume_path }}" "luks-{{ item.mount_path | basename }}"
    creates: "/dev/mapper/luks-{{ item.mount_path | basename }}"

- name: Mount disks.
  loop: "{{ mount_disks }}"
  no_log: true
  ansible.posix.mount:
    path: "{{ item.mount_path }}"
    src: "/dev/mapper/luks-{{ item.mount_path | basename }}"
    fstype: ext4
    opts: user,rw,noatime,noauto,exec
    boot: false
    state: mounted
