---
- name: Verify
  hosts: all
  vars:
    expected_mergerfs_version: '2.42.0'
  tasks:
    - name: Check mergerfs is installed.
      ansible.builtin.command:
        cmd: mergerfs --version
      register: mergerfs_version_output
      changed_when: false

    - name: Assert mergerfs reported the expected version.
      ansible.builtin.assert:
        that:
          - expected_mergerfs_version in mergerfs_version_output.stdout
