---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - mergerfs_pool is not none
      - mergerfs_version is not none

- name: Assert that mergerfs_cached_pool is defined when mergerfs_cache_disk is defined.
  when: mergerfs_caching_enabled is not false
  ansible.builtin.assert:
    that:
      - mergerfs_cache_disk is not none
      - mergerfs_cached_pool is not none

- name: Install fuse.
  ansible.builtin.package:
    name: fuse
    state: present
    update_cache: true

- name: Setting architecture to amd64.
  ansible.builtin.set_fact:
    download_arch: "amd64"
  when: '"x86_64" in ansible_architecture'

- name: Setting architecture to arm64.
  ansible.builtin.set_fact:
    download_arch: "arm64"
  when: '"armv" in ansible_architecture or "aarch" in ansible_architecture'

- name: Setting architecture to armhf.
  ansible.builtin.set_fact:
    download_arch: "armhf"
  when: '"armv7l" in ansible_architecture'

- name: Downloading mergerfs .deb package.
  ansible.builtin.get_url:
    url: "https://github.com/trapexit/mergerfs/releases/download/\
      {{ mergerfs_version }}/\
      mergerfs_{{ mergerfs_version }}.{{ ansible_distribution }}-\
      {{ ansible_distribution_release }}_{{ download_arch }}.deb"
    dest: /tmp/mergerfs.deb
    mode: '0644'

- name: Install mergerfs from download .deb package.
  ansible.builtin.apt:
    deb: /tmp/mergerfs.deb

- name: Make sure mountpoint exists.
  ansible.builtin.file:
    path: "{{ mergerfs_pool }}"
    state: directory
    mode: '0755'

- name: Make sure disk paths exist.
  with_items: "{{ mergerfs_disks }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'

- name: Mount mergerfs filesystems
  when: mergerfs_disks | length > 0
  ansible.builtin.mount:
    fstype: fuse.mergerfs
    src: "{{ ':'.join(mergerfs_disks) }}"
    path: "{{ mergerfs_pool }}"
    opts: "minfreespace={{ mergerfs_min_free_space }},\
      fsname={{ mergerfs_pool | basename }},\
      allow_other,\
      use_ino,\
      cache.files=partial,\
      dropcacheonclose=true,\
      category.create=mfs,\
      moveonenospc=true,\
      noauto"
    state: mounted

- name: When mergerfs_cache_disk is defined.
  when: mergerfs_caching_enabled is not false
  block:
    - name: Make sure mergerfs_cache_disk path exists.
      ansible.builtin.file:
        path: "{{ mergerfs_cache_disk }}"
        state: directory
        mode: '0755'

    - name: Make sure cached path exists.
      ansible.builtin.file:
        path: "{{ mergerfs_cached_pool }}"
        state: directory
        mode: '0755'

    - name: Add mergerfs_cache_disk to mergerfs_disks
      ansible.builtin.set_fact:
        mergerfs_disks_combined: "{{ [mergerfs_cache_disk] + mergerfs_disks }}"

    - name: Mount mergerfs filesystems
      when: mergerfs_disks | length > 0
      ansible.builtin.mount:
        fstype: fuse.mergerfs
        src: "{{ ':'.join(mergerfs_disks_combined) }}"
        path: "{{ mergerfs_cached_pool }}"
        opts: "minfreespace={{ mergerfs_min_free_space }},\
          fsname={{ mergerfs_cached_pool | basename }},\
          allow_other,\
          use_ino,\
          cache.files=partial,\
          dropcacheonclose=true,\
          category.create=mfs,\
          moveonenospc=true,\
          noauto"
        state: mounted
