---
- name: Converge
  hosts: all
  vars:
    tesseract_username: tesseract
    shares_host: 127.0.0.1
    shares_path: /media/shares
    tesseract_samba_password: password
    shares:
      - name: public
        read_only: false
  roles:
    - role: tesseract.system.shares
