---
- name: Verify
  hosts: all
  tasks:

    - name: Check that cryptsetup is installed.
      ansible.builtin.command:
        cmd: cryptsetup --version
      changed_when: false
      register: cryptsetup_version
      failed_when: cryptsetup_version.rc != 0
