---

provision_scripts_repo: https://github.com/ben16w/tesseract-common.git
provision_scripts_version: main
provision_scripts_path: /opt/common
provision_scripts_subdir: scripts

provision_volumes: []
  # - volume_file: "/path/to/file.image"
  #   generate_data: true
  #   size: 2G
  #   password: "password"
