---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - tesseract_username is not none
      - tesseract_password is not none
      - tesseract_hostname is not none
      - admin_password is not none

- name: Set hostname.
  ansible.builtin.hostname:
    name: "{{ tesseract_hostname }}"

- name: Set localhost entry in /etc/host.
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ tesseract_hostname }}"
    line: "127.0.0.1 {{ tesseract_hostname }}"
    owner: root
    group: root
    mode: 0644

# Set date and time?

- name: Update & upgrade OS.
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 21600 # 6 Hours

- name: Install common software.
  ansible.builtin.apt:
    pkg:
      - python3-setuptools
      - python3-pip
      - ntp
      - net-tools
      - rsync
      - unzip
      - git
      - zip
      - wakeonlan

- name: Install setuptools and passlib using pip.
  ansible.builtin.pip:
    name:
      - setuptools
      - passlib

- name: Set nano as default editor for root.
  ansible.builtin.lineinfile:
    path: /root/.selected_editor
    search_string: SELECTED_EDITOR=
    line: SELECTED_EDITOR="/bin/nano"
    create: true
    owner: root
    group: root
    mode: '0644'

- name: Set admin user.
  ansible.builtin.user:
    name: "{{ admin_username }}"
    comment: "admin user"
    shell: /bin/bash
#   group: admin
    groups:
      - sudo
    append: true
    generate_ssh_key: true
    password: "{{ admin_password | password_hash('sha512', 65534 | random(seed=tesseract_hostname) | string) }}"

- name: Ensure tesseract group exists.
  ansible.builtin.group:
    name: "{{ tesseract_username }}"
    state: present

- name: Set tesseract user.
  ansible.builtin.user:
    name: "{{ tesseract_username }}"
    comment: "tesseract user"
    shell: /bin/bash
    group: tesseract
    generate_ssh_key: false
    password: "{{ tesseract_password | password_hash('sha512', 65534 | random(seed=tesseract_hostname) | string) }}"

- name: Make sure tesseract is removed from sudoers.
  ansible.builtin.command:
    cmd: "/usr/sbin/deluser {{ tesseract_username }} sudo"
  register: grp_change
  failed_when: grp_change.rc not in [0, 6]
  changed_when: grp_change.rc == 0

- name: Remove pi sudoers file found on RPi.
  notify: restart sshd
  ansible.builtin.file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent

- name: Disable root login.
  notify: restart sshd
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin No'

- name: Add SFTP server config.
  no_log: true
  notify: restart sshd
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    create: true
    owner: root
    group: root
    mode: 0644
    block: |
      Match user {{ tesseract_username }}
        ChrootDirectory /media
        X11Forwarding no
        AllowTcpForwarding no
        ForceCommand internal-sftp


# The stuff below should be in seperate roles.

- name: Install fail2ban.
  ansible.builtin.apt:
    pkg:
      - fail2ban

- name: Template fail2ban configuration.
  ansible.builtin.template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Make sure fail2ban is enabled and started.
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
