---

rsync_backup_log_file: /var/log/tesseract.log
rsync_backup_scripts_path: /opt/tesseract/scripts

rsync_backup_scripts_repo: https://github.com/ben16w/tesseract-scripts.git

rsync_backup_paths: []

rsync_backup_destination: /media/backups

rsync_backup_max_backups: 10

rsync_backup_minute: 0
rsync_backup_hour: 0
rsync_backup_day: "*"

tesseract_email_host: ~
tesseract_email_port: ~
tesseract_email_username: ~
tesseract_email_password: ~
