---
- name: Install python3-debian for deb822_repository.
  ansible.builtin.apt:
    name: python3-debian
    state: present
    update_cache: true

- name: Add kisak-mesa PPA repository for Ubuntu.
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.deb822_repository:
    name: kisak-mesa
    types: deb
    uris: https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF63F0F2B90935439"
    state: present

- name: Install Mesa Vulkan drivers and related packages.
  ansible.builtin.apt:
    name:
      - mesa-vulkan-drivers
      - vulkan-tools
      - mesa-utils
    state: present
    update_cache: true

- name: Install VA-API drivers for Intel.
  ansible.builtin.apt:
    name:
      - intel-media-va-driver
      - vainfo
    state: present
