---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - gpu_rocm_version_short is not none
      - gpu_rocm_version_long is not none

- name: Check if the distribution is Ubuntu.
  ansible.builtin.assert:
    that:
      - ansible_distribution == 'Ubuntu'

- name: Ensure render and video groups exist.
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
    system: true
  loop:
    - render
    - video

- name: Add the tesseract user to the render and video groups.
  ansible.builtin.user:
    name: "{{ tesseract_username }}"
    groups:
      - render
      - video
    append: true

- name: Install necessary Linux headers and modules.
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - "linux-modules-extra-{{ ansible_kernel }}"
    state: present
    update_cache: true

- name: Check if ROCm is already installed at the target version.
  ansible.builtin.command:
    cmd: "dpkg-query -W -f='${Version}' rocm"
  register: rocm_installed_version
  failed_when: false
  changed_when: false

- name: Download and install ROCm if required.
  when: >
    rocm_installed_version.rc != 0 or
    gpu_rocm_version_short not in rocm_installed_version.stdout
  block:
    - name: Download the AMDGPU driver package.
      ansible.builtin.get_url:
        url: "https://repo.radeon.com/amdgpu-install/\
          {{ gpu_rocm_version_short }}/ubuntu/\
          {{ ansible_distribution_release }}/amdgpu-install_\
          {{ gpu_rocm_version_long }}_all.deb"
        dest: /tmp/amdgpu-install.deb
        owner: root
        group: root
        mode: '0644'
      register: download_driver
      retries: 5
      delay: 10
      until: download_driver is succeeded

    - name: Install the AMDGPU driver package.
      ansible.builtin.apt:
        deb: /tmp/amdgpu-install.deb

    - name: Run amdgpu-install script to finalize installation.
      ansible.builtin.command:
        cmd: "amdgpu-install --usecase=rocm --accept-eula -y"
      register: amdgpu_install_result
      changed_when: true
      failed_when: >
        amdgpu_install_result.rc != 0 and
        'amdgpu-proprietary.list: No such file or directory' not in amdgpu_install_result.stderr

- name: Get current Ollama version.
  ansible.builtin.command: ollama --version
  register: ollama_current_version
  failed_when: false
  changed_when: false

- name: Check if ROCm Ollama payload is already installed.
  ansible.builtin.stat:
    path: /usr/lib/ollama/rocm
  register: ollama_rocm_package_installed

- name: Download and install Ollama ROCm package if required.
  when:
    - gpu_ollama_version is not none
    - gpu_ollama_version not in ollama_current_version.stdout or not ollama_rocm_package_installed.stat.exists
  block:
    - name: Download the ROCm package to /tmp.
      ansible.builtin.get_url:
        url: "https://github.com/ollama/ollama/releases/download/v{{ gpu_ollama_version }}/ollama-linux-{{ arch }}-rocm.tgz"
        dest: "/tmp/ollama-linux-{{ arch }}-rocm.tgz"
        owner: root
        group: root
        mode: '0644'
      register: download_rocm
      retries: 5
      delay: 10
      until: download_rocm is succeeded

    - name: Extract ROCm package to /usr.
      ansible.builtin.unarchive:
        src: "/tmp/ollama-linux-{{ arch }}-rocm.tgz"
        dest: /usr
        remote_src: true
        owner: root
        group: root
        mode: '0755'
