---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - gpu_amd_version_short is not none
      - gpu_amd_version_long is not none

- name: Install necessary Linux headers and modules.
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - "linux-modules-extra-{{ ansible_kernel }}"
    state: present

- name: Check if ROCm is already installed at the target version.
  ansible.builtin.command:
    cmd: "dpkg-query -W -f='${Version}' rocm"
  register: amd_installed_version
  failed_when: false
  changed_when: false

- name: Download and install ROCm if required.
  when: >
    amd_installed_version.rc != 0 or
    gpu_amd_version_short not in amd_installed_version.stdout
  block:
    - name: Download the AMDGPU driver package.
      ansible.builtin.get_url:
        url: "https://repo.radeon.com/amdgpu-install/\
          {{ gpu_amd_version_short }}/ubuntu/\
          {{ ansible_distribution_release }}/amdgpu-install_\
          {{ gpu_amd_version_long }}_all.deb"
        dest: /tmp/amdgpu-install.deb
        owner: root
        group: root
        mode: '0644'
        force: true
      register: download_driver
      retries: 5
      delay: 10
      until: download_driver is succeeded

    - name: Install the AMDGPU driver package.
      ansible.builtin.apt:
        deb: /tmp/amdgpu-install.deb

    - name: Run amdgpu-install script to finalize installation.
      ansible.builtin.command:
        cmd: "amdgpu-install --usecase=graphics,rocm --accept-eula -y"
      register: amdgpu_install_result
      changed_when: true
      failed_when: >
        amdgpu_install_result.rc != 0 and
        'amdgpu-proprietary.list: No such file or directory' not in amdgpu_install_result.stderr

- name: Install VA-API drivers for AMD.
  ansible.builtin.apt:
    name:
      - mesa-va-drivers
      - libva-utils
    state: present
