---
- name: Converge
  hosts: all
  vars:
    email_username: "email@email.com"
    email_host: "email.com"
    email_port: "465"
    email_password: "password"

    mirror_backup_paths:
      - /tmp/data
  roles:
    - role: mirror_backup
